name: Build binary package

on:
  workflow_dispatch:
    inputs:
      release_body:
        description: 'Release 描述（可选）'
        required: false
        default: ''

jobs:
  build:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            use_cross: false
          - os: windows-latest
            target: i686-pc-windows-msvc
            use_cross: false
          - os: macos-latest
            target: x86_64-apple-darwin
            use_cross: false
          - os: macos-latest
            target: aarch64-apple-darwin
            use_cross: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install OpenSSL dev (for Linux GNU targets)
        if: startsWith(matrix.os, 'ubuntu') && matrix.target == 'x86_64-unknown-linux-gnu'
        run: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package
        run: |
          mkdir dist
          cp target/${{ matrix.target }}/release/quarkdrive-webdav* dist/ || cp target/${{ matrix.target }}/release/quarkdrive-webdav.exe dist/
          cd dist
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            7z a ../quarkdrive-webdav-${{ matrix.target }}.zip *
          else
            tar czf ../quarkdrive-webdav-${{ matrix.target }}.tar.gz *
          fi

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            quarkdrive-webdav-${{ matrix.target }}.*
          body: ${{ github.event.inputs.release_body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 设置 Release 名称
        id: release_vars
        run: |
          echo "name=${{ github.ref_name }}" >> $GITHUB_OUTPUT